### PR TITLE
fix: make build for metal work

### PR DESCRIPTION
**Pull request by polvalente**
Still needs validation for CUDA and CPU builds

### CODE REVIEW

**Comment by josevalim** [comment]
Shall we include the metal plugin so no additional downloads are required on EXLA side?

**Comment by polvalente** [comment]
It seems to be closed source, so I'm not exactly sure how to go about that...

**Comment by josevalim** [comment]
Gah, now I am getting cold feet too. If using metal means we cannot upgrade XLA until there is a new metal version and that we need to package closed source code, then perhaps it is not worth doing it until Apple decides to provide an open source version that does not pin jaxlib/xla.

**Comment by jonatanklosko** [comment]
> If using metal means we cannot upgrade XLA until there is a new metal version

I definitely agree, I would at least wait with releasing the integration until the metal plugin is updated to latest jax. But if it stays closed source and pinned then committing to maintaining the compatibility may hold as back, so it is tough.

**Comment by polvalente** [comment]
Let's close this for now. We'll work on the MLIR EXLA compiler regardless

**Pull request closed without merging**
